version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 100
    directory: /
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/aws/accounts/audit
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/aws/accounts/auth
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/aws/accounts/dev
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/aws/accounts/prod
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/aws/accounts/root
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/aws/common/organization
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/cloudflare
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/github
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/tailscale
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino

  - package-ecosystem: terraform
    open-pull-requests-limit: 100
    directory: terraform/terraform
    schedule:
      time: "08:00"
      timezone: "America/Los_Angeles"
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - lingrino
