service: ami-cleaner

provider:
  name: aws
  runtime: go1.x
  versionFunctions: true
  stackTags:
    service: serverless
    serverless: "true"

  stage: ${opt:stage, "prod"}
  region: ${opt:region, "us-east-1"}

  timeout: 120
  memorySize: 128
  logRetentionInDays: 90

  deploymentBucket:
    name: ${ssm:/s3/serverless-deployment/name}
    serverSideEncryption: AES256
    tags:
      service: serverless
      serverless: "true"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:DescribeImages
        - ec2:DescribeInstances
        - ec2:DeregisterImage
        - ec2:DeleteSnapshot
      Resource: "*"

  tags:
    service: serverless
    serverless: "true"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  ami-cleaner:
    name: ${self:service}
    description: cleans up unused AMIs
    handler: bin/ami-cleaner
    events:
      - schedule:
          name: ${self:service}
          description: cleans up unused AMIs
          rate: cron(0 17 * * ? *)
    onError: arn:aws:sns:us-east-1:418875065733:alarm_low_priority
